# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Prompt-wide configuration options
command_timeout = 1000

# NOTE: Preset examples: https://starship.rs/presets/
# also see https://github.com/starship/starship/tree/8b6177c72819510b42923e7b72deca2e4356efe2/docs/public/presets/toml

# Format see https://starship.rs/config/#default-prompt-format
format = """
[î‚¶](#1b1f23)\
$os\
$username\
[î‚´ ](#1b1f23)\
$directory\
$git_branch\
$git_status\
$fill\
$docker_context\
$jobs\
$package\
$c\
$cmake\
$cobol\
$deno\
$golang\
$haskell\
$helm\
$java\
$kotlin\
$kubernetes\
$lua\
$nodejs\
$python\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vagrant\
$zig\
$buf\
$aws\
$gcloud\
$openstack\
$azure\
$direnv\
$env_var\
$sudo\
$cmd_duration\
$line_break\
$character"""

[fill]
symbol = ' '

# Palettes
# TODO create palettes to re-use colors and toggle themes

# Moduless
[os]
disabled = false
style = "bg:#1b1f23 fg:#cdd6f4"

[os.symbols]
Windows = "ó°²"
Ubuntu = "ó°•ˆ"
SUSE = "ïŒ”"
Raspbian = "ó°¿"
Mint = "ó°£­"
Macos = "ïŒ‚" 
Manjaro = "ïŒ’"
Linux = "ó°Œ½"
Gentoo = "ó°£¨"
Fedora = "ó°£›"
Alpine = "ïŒ€"
Amazon = "ï‰°"
Android = "îœ"
Arch = "ó°£‡"
Artix = "ó°£‡"
CentOS = "ïŒ„"
Debian = "ó°£š"
Redhat = "ó±„›"
RedHatEnterprise = "ó±„›"

[username]
show_always = true
style_user = "bg:#1b1f23 fg:#cdd6f4"
style_root = "bg:#1b1f23 fg:#cdd6f4"
format = '[ $user ]($style)'

# Language Modules
[c]
symbol = "î˜ "

[rust]
symbol = "î¨"

[golang]
symbol = "ó°Ÿ“ î˜§"

[java]
symbol = "î‰–"

[kotlin]
symbol = "î˜´"

[nodejs]
symbol = "îœ˜ " 

[deno]
symbol = "ğŸ¦•|ó°›¦"

[ruby]
symbol = "î‘"

[terraform]
symbol = "îšš"

[vagrant]
symbol = "V"

[aws]
symbol = "ó°¸"
