# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Prompt-wide configuration options
command_timeout = 750

# NOTE: Preset examples: https://starship.rs/presets/
# also see https://github.com/starship/starship/tree/8b6177c72819510b42923e7b72deca2e4356efe2/docs/public/presets/toml

# Format see https://starship.rs/config/#default-prompt-format
format = """
[î‚¶](surface0)\
$os\
$username\
[î‚´ ](surface0)\
$directory\
$git_branch\
$git_status\
$fill\
$docker_context\
$jobs\
$package\
$c\
$deno\
$bun\
$nodejs\
$golang\
$helm\
$java\
$kotlin\
$kubernetes\
$lua\
$python\
$ruby\
$rust\
$swift\
$terraform\
$vagrant\
$zig\
$buf\
$aws\
$gcloud\
$openstack\
$azure\
$direnv\
$env_var\
$sudo\
$cmd_duration\
$line_break\
$character"""

palette = 'github_dark'

[fill]
symbol = ' '

# Palettes
[palettes.github_dark]
surface0 = "#0d1117"
surface1 = "#1b1f23"
text = "#c9d1d9"
accent = "#F78166"
black = "#0d1117"
blue = "#58a6ff"
cyan = "#76e3ea"
green = "#3fb950"
magenta = "#bc8cff"
red = "#ff7b72"
white = "#b1bac4"
yellow = "#d29922"
bright_black = "#161b22"
bright_blue = "#79c0ff"
bright_cyan = "#b3f0ff"
bright_green = "#56d364"
bright_magenta = "#d2a8ff"
bright_red = "#ffa198"
bright_white = "#b1bac4"
bright_yellow = "#e3b341"

# Moduless
[os]
disabled = false
style = "bg:surface0 fg:text"

[os.symbols]
Windows = "ó°²"
Ubuntu = "ó°•ˆ"
SUSE = "ïŒ”"
Raspbian = "ó°¿"
Mint = "ó°£­"
Macos = "ïŒ‚" 
Manjaro = "ïŒ’"
Linux = "ó°Œ½"
Gentoo = "ó°£¨"
Fedora = "ó°£›"
Alpine = "ïŒ€"
Amazon = "ï‰°"
Android = "îœ"
Arch = "ó°£‡"
Artix = "ó°£‡"
CentOS = "ïŒ„"
Debian = "ó°£š"
Redhat = "ó±„›"
RedHatEnterprise = "ó±„›"

[username]
show_always = true
style_user = "bg:surface0 fg:text"
style_root = "bg:surface0 fg:text"
format = '[ $user]($style)'

# Language Modules
[c]
symbol = "î˜"
format = "[$symbol ($version)]($style) "

[rust]
symbol = "î¨"
format = "[$symbol ($version)]($style) "

[zig]
symbol = "îš©"
format = "[$symbol ($version)]($style) "

[golang]
symbol = "ó°Ÿ“"
format = "[$symbol ($version)]($style) "

[java]
symbol = "î‰–"
format = "[$symbol ($version)]($style) "

[kotlin]
symbol = "î˜´"
format = "[$symbol ($version)]($style) "

[lua]
symbol = "î˜ "
format = "[$symbol ($version)]($style) "

[nodejs]
symbol = "îœ˜"
format = "[$symbol ($version)]($style) "

[deno]
symbol = "DenoğŸ¦•|ó°›¦"
format = "[$symbol ($version)]($style) "

[bun]
symbol = "BunğŸ¥Ÿ|ó°›¦"
format = "[$symbol ($version)]($style) "

[ruby]
symbol = "î‘"
format = "[$symbol ($version)]($style) "

[python]
symbol = "îœ¼"
format = "[$symbol ($version)]($style) "

[swift]
symbol = "î•"
format = "[$symbol ($version)]($style) "

[docker_context]
symbol = "ğŸ³"
format = "[$symbol ($context)]($style) " 

[terraform]
symbol = "îšš"
format = "[$symbol ($version)]($style) "

[vagrant]
symbol = "â±"
format = "[$symbol ($version)]($style) "

[aws]
symbol = "ó°¸"
format = "[$symbol ($version)]($style) "

